---
jupyter: python3
title: "Conclusion"
date: "11/07/2022"
pdf-engine: lualatex
format:
  html:
    theme : Minty
    toc: true
    toc-title: Contents
    bibliography: references.bib
execute:
    warning: false
---
Remember that before we officially started to cluster the data, we manually subset the data and removed the true label (targets) from the data. In our original data, each observation represents an insurance buyer, and the true label is the type of insurance they purchased: Catastrophic, Deductible, Coinsurance, and Free. Our true label has four classes, while our cluster results show three distinct clusters. This is not because we did not cluster the data well, but is suggesting us that our data can have more than one structure (label), other than insurance plan type. Based on different cluster result, we can have different ways to seperate our X features.

Clustering is very useful in real-life application. In marketing, companies cluster their customer to get to know the customer's satisfaction with their product so that a better decision-making process can be done. In pharmacy, patients in different cluster can be given different test to examine the medicine, so medicines can be made to target different patients. For software development industry, companies cluster the search result so that everytime user is searching something particular online, the results are a mixture of the similar matches of your original query. 


## References
Hickman, James. “ANLY501 Week-11 Clustering .” ANLY501, 2 Nov. 2022, D.C, Georgetown University. 

Kumar, Satyam. Clustering Agglomerative Process | towards Data Science. Towards Data Science, 3 Aug. 2022, https://towardsdatascience.com/breaking-down-the-agglomerative-clustering-process-1c367f74c7c2. 

Shaik, Janibasha. “Practical Implementation of K-Means, Hierarchical, and DBSCAN Clustering on Dataset with...” Medium, Analytics Vidhya, 18 Sept. 2020, https://medium.com/analytics-vidhya/practical-implementation-of-k-means-hierarchical-and-dbscan-clustering-on-dataset-with-bd7f3d13ef7f. 


